// Auto-generated file created by react-native-storybook-loader
// Do not edit.
//
// https://github.com/elderfo/react-native-storybook-loader.git

function loadStories() {
  require('../src/community-integrations/ReactHookForm/index.stories')
  require('../src/components/basic/FlatList/index.stories')
  require('../src/components/basic/KeyboardAvoidingView/index.stories')
  require('../src/components/basic/ScrollView/index.stories')
  require('../src/components/basic/SectionList/index.stories')
  require('../src/components/basic/StatusBar/index.stories')
  require('../src/components/basic/View/index.stories')
  require('../src/components/composites/Accordion/index.stories')
  require('../src/components/composites/Actionsheet/Actionsheet.stories')
  require('../src/components/composites/Alert/index.stories')
  require('../src/components/composites/AlertDialog/index.stories')
  require('../src/components/composites/AppBar/index.stories')
  require('../src/components/composites/AspectRatio/index.stories')
  require('../src/components/composites/Avatar/index.stories')
  require('../src/components/composites/Badge/index.stories')
  require('../src/components/composites/Breadcrumb/index.stories')
  require('../src/components/composites/Card/index.stories')
  require('../src/components/composites/Center/index.stories')
  require('../src/components/composites/CircularProgress/index.stories')
  require('../src/components/composites/Collapse/index.stories')
  require('../src/components/composites/Container/index.stories')
  require('../src/components/composites/Divider/index.stories')
  require('../src/components/composites/Drawer/index.stories')
  require('../src/components/composites/Fab/index.stories')
  require('../src/components/composites/factory/index.stories')
  require('../src/components/composites/FormControl/index.stories')
  require('../src/components/composites/IconButton/index.stories')
  require('../src/components/composites/Menu/index.stories')
  require('../src/components/composites/Modal/index.stories')
  require('../src/components/composites/NumberInput/index.stories')
  require('../src/components/composites/PinInput/index.stories')
  require('../src/components/composites/Popover/index.stories')
  require('../src/components/composites/Progress/index.stories')
  require('../src/components/composites/SimpleGrid/index.stories')
  require('../src/components/composites/Skeleton/index.stories')
  require('../src/components/composites/Tabs/index.stories')
  require('../src/components/composites/Tag/index.stories')
  require('../src/components/composites/TextField/index.stories')
  require('../src/components/composites/Toast/index.stories')
  require('../src/components/composites/Tooltip/index.stories')
  require('../src/components/composites/Transitions/index.stories')
  require('../src/components/composites/Typeahead/index.stories')
  require('../src/components/composites/Wrap/index.stories')
  require('../src/components/perf/index.stories')
  require('../src/components/primitives/Box/index.stories')
  require('../src/components/primitives/Button/index.stories')
  require('../src/components/primitives/Button2/Button.stories')
  require('../src/components/primitives/ButtonGroup/index.stories')
  require('../src/components/primitives/Checkbox/index.stories')
  require('../src/components/primitives/Flex/index.stories')
  require('../src/components/primitives/Heading/index.stories')
  require('../src/components/primitives/Hidden/index.stories')
  require('../src/components/primitives/HStack/index.stories')
  require('../src/components/primitives/Icon/index.stories')
  require('../src/components/primitives/Image/index.stories')
  require('../src/components/primitives/Input/index.stories')
  require('../src/components/primitives/Link/index.stories')
  require('../src/components/primitives/List/index.stories')
  require('../src/components/primitives/Pressable/index.stories')
  require('../src/components/primitives/Radio/index.stories')
  require('../src/components/primitives/Select/index.stories')
  require('../src/components/primitives/Slider/index.stories')
  require('../src/components/primitives/Spinner/index.stories')
  require('../src/components/primitives/Stack/index.stories')
  require('../src/components/primitives/Switch/index.stories')
  require('../src/components/primitives/Text/index.stories')
  require('../src/components/primitives/TextArea/index.stories')
  require('../src/components/primitives/View/index.stories')
  require('../src/components/primitives/VStack/index.stories')
  require('../src/components/primitives/ZStack/index.stories')
}

const stories = [
  '../src/community-integrations/ReactHookForm/index.stories',
  '../src/components/basic/FlatList/index.stories',
  '../src/components/basic/KeyboardAvoidingView/index.stories',
  '../src/components/basic/ScrollView/index.stories',
  '../src/components/basic/SectionList/index.stories',
  '../src/components/basic/StatusBar/index.stories',
  '../src/components/basic/View/index.stories',
  '../src/components/composites/Accordion/index.stories',
  '../src/components/composites/Actionsheet/Actionsheet.stories',
  '../src/components/composites/Alert/index.stories',
  '../src/components/composites/AlertDialog/index.stories',
  '../src/components/composites/AppBar/index.stories',
  '../src/components/composites/AspectRatio/index.stories',
  '../src/components/composites/Avatar/index.stories',
  '../src/components/composites/Badge/index.stories',
  '../src/components/composites/Breadcrumb/index.stories',
  '../src/components/composites/Card/index.stories',
  '../src/components/composites/Center/index.stories',
  '../src/components/composites/CircularProgress/index.stories',
  '../src/components/composites/Collapse/index.stories',
  '../src/components/composites/Container/index.stories',
  '../src/components/composites/Divider/index.stories',
  '../src/components/composites/Drawer/index.stories',
  '../src/components/composites/Fab/index.stories',
  '../src/components/composites/factory/index.stories',
  '../src/components/composites/FormControl/index.stories',
  '../src/components/composites/IconButton/index.stories',
  '../src/components/composites/Menu/index.stories',
  '../src/components/composites/Modal/index.stories',
  '../src/components/composites/NumberInput/index.stories',
  '../src/components/composites/PinInput/index.stories',
  '../src/components/composites/Popover/index.stories',
  '../src/components/composites/Progress/index.stories',
  '../src/components/composites/SimpleGrid/index.stories',
  '../src/components/composites/Skeleton/index.stories',
  '../src/components/composites/Tabs/index.stories',
  '../src/components/composites/Tag/index.stories',
  '../src/components/composites/TextField/index.stories',
  '../src/components/composites/Toast/index.stories',
  '../src/components/composites/Tooltip/index.stories',
  '../src/components/composites/Transitions/index.stories',
  '../src/components/composites/Typeahead/index.stories',
  '../src/components/composites/Wrap/index.stories',
  '../src/components/perf/index.stories',
  '../src/components/primitives/Box/index.stories',
  '../src/components/primitives/Button/index.stories',
  '../src/components/primitives/Button2/Button.stories',
  '../src/components/primitives/ButtonGroup/index.stories',
  '../src/components/primitives/Checkbox/index.stories',
  '../src/components/primitives/Flex/index.stories',
  '../src/components/primitives/Heading/index.stories',
  '../src/components/primitives/Hidden/index.stories',
  '../src/components/primitives/HStack/index.stories',
  '../src/components/primitives/Icon/index.stories',
  '../src/components/primitives/Image/index.stories',
  '../src/components/primitives/Input/index.stories',
  '../src/components/primitives/Link/index.stories',
  '../src/components/primitives/List/index.stories',
  '../src/components/primitives/Pressable/index.stories',
  '../src/components/primitives/Radio/index.stories',
  '../src/components/primitives/Select/index.stories',
  '../src/components/primitives/Slider/index.stories',
  '../src/components/primitives/Spinner/index.stories',
  '../src/components/primitives/Stack/index.stories',
  '../src/components/primitives/Switch/index.stories',
  '../src/components/primitives/Text/index.stories',
  '../src/components/primitives/TextArea/index.stories',
  '../src/components/primitives/View/index.stories',
  '../src/components/primitives/VStack/index.stories',
  '../src/components/primitives/ZStack/index.stories',
]

module.exports = {
  loadStories,
  stories,
}
